-- MySQL Script generated by MySQL Workbench
-- Wed Aug 25 09:54:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`department` (
  `id_dep` INT NOT NULL,
  `name_dep` VARCHAR(45) NULL,
  PRIMARY KEY (`id_dep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emplyee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emplyee` (
  `id_emp` INT NOT NULL,
  `name_emp` VARCHAR(45) NULL,
  `position_emp` VARCHAR(45) NULL,
  `bossid_emp` INT NULL,
  `date_emp` DATE NULL,
  `salary_emp` INT NULL,
  `oversal_emp` INT NULL,
  `department_id_dep` INT NOT NULL,
  PRIMARY KEY (`id_emp`),
  INDEX `fk_emplyee_department_idx` (`department_id_dep` ASC) VISIBLE,
  CONSTRAINT `fk_emplyee_department`
    FOREIGN KEY (`department_id_dep`)
    REFERENCES `mydb`.`department` (`id_dep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
